---
gcp:
  project_id: oranrag
  location: us-central1
  bucket_name: oran-rag-bucket-us-central
  embeddings_path: "embeddings/"
  bucket_uri: "gs://oran-rag-bucket-us-central/embeddings/"
  qna_dataset_path: "dataset/Q&A_ds_H.json"
  credentials_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/oranrag-8487e5b44925.json"
paths:
  documents: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/Documents/"
  embeddings_save_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/Embeddings/"
vector_search:
  index_display_name: oran_rag_index_stream_2
  endpoint_display_name: oran_rag_index_endpoint
  deployed_index_id: oran_rag_index_deployed
  index_description: "Index for O-RAN document embeddings"
  dimensions: 768
  approximate_neighbors_count: 5
  leaf_node_embedding_count: 500
  leaf_nodes_to_search_percent: 7
  distance_measure_type: COSINE_DISTANCE
  feature_norm_type: UNIT_L2_NORM
  update_method: STREAM_UPDATE
  shard_size: SHARD_SIZE_SMALL
  machine_type: e2-standard-2
  min_replica_count: 2
  max_replica_count: 2
  num_neighbors: 10
  reranker_type: rank_service
  reranker_model_name: semantic-ranker-512@latest
  rag_corpus_resource: "projects/oranrag/locations/us-central1/ragCorpora/9144559043375792128"
  rag_corpus_display_name: O-RAN-RAG-Corpus-2
  rag_corpus_description: "Corpus for O-RAN RAG Pipeline"
  vector_db_config:
    vertex_vector_search:
      index: "projects/350296334322/locations/us-central1/indexes/1549480164373561344"
      index_endpoint: "projects/350296334322/locations/us-central1/indexEndpoints/5973633479567474688"
chunking:
  chunk_size: 1536
  chunk_overlap: 256
  separators:
  - ". "
  - "? "
  - "! "
  - '


    '
  min_char_count: 100
embedding:
  embedding_model_name: text-embedding-004
  publisher_model: "publishers/google/models/text-embedding-004"
generation:
  temperature: 0.7
  top_p: 0.9
  max_output_tokens: 2000
  generative_model_name: gemini-1.5-flash-002
logging:
  log_file: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/log/oran_rag.log"
evaluation:
  num_questions: 3243
  excel_file_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/Evaluation/evaluation_results.xlsx"
  max_workers: 1
  plot_save_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/Evaluation/accuracy_plots.png"
...
