gcp:
  project_id: "oran-rag"
  location: "us-central1"
  bucket_name: "oran-rag-bucket"
  embeddings_path: "embeddings/"
  bucket_uri: "gs://oran-rag-bucket/embeddings/"
  qna_dataset_path: "dataset/fin_H.json"
  credentials_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My\ Drive/1.Projects/ORAN_RAG/keys/oran-rag-01462ea53452.json"

paths:
  documents: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/raw_docs"
  embeddings_save_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/chunks_output"

vector_search:
  index_display_name: "oran_rag_contextual_index"  # Name for the index creation
  endpoint_display_name: "oran_rag_contextual_endpoint"  # Name for the index deployment
  deployed_index_id: "oran_rag_contextual_index__1743254548226" # Name for the deployed index

  # Parameters for index creation
  index_description: "Index for O-RAN document embeddings"
  dimensions: 768
  approximate_neighbors_count: 5
  leaf_node_embedding_count: 500
  leaf_nodes_to_search_percent: 7
  distance_measure_type: "COSINE_DISTANCE"
  feature_norm_type: "UNIT_L2_NORM"
  shard_size: "SHARD_SIZE_SMALL"

  #Parameters for index deployment
  machine_type: "e2-standard-2"
  min_replica_count: 2
  max_replica_count: 2

  # Parameters for search
  num_neighbors: 40

ranking:
  ranking_config: "default_ranking_config"  
  model: "semantic-ranker-512@latest" 
  rerank_top_n: 20

chunking:
  chunk_size: 1536  # Maximum number of characters per chunk
  chunk_overlap: 256  # Number of overlapping characters between chunks
  separators: [". ", "? ", "! ", "\n\n"]
  min_char_count: 100

generation:
  temperature: 0.3
  top_p: 0.9
  max_output_tokens: 8192

logging:
  log_file: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/logs/contextual_chunking.log"  # User-defined path for log files

evaluation:
  num_questions: 3243
  qna_dataset_local_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/evaluation_dataset/validation_set_2.json"
  excel_file_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/evaluation_results/contextual_chunking/evaluation_results.xlsx"
  max_workers: 1
  plot_save_path: "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/evaluation_results/contextual_chunking/accuracy_plots.png"